### PR TITLE
Drop async

### PR DESCRIPTION
**Pull request by TrySound**
Async package is quite big (especially v2 with lodash in dependencies).
In this diff I replaced it with simple promise flow.

https://packagephobia.com/result?p=async

# License
I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by TrySound** [comment]
@Gerdie rebased

**Comment by TrySound** [comment]
Hi @Gerdie Does this look good to you?

**Comment by TrySound** [comment]
Friendly ping @Gerdie

**Review by sdwvit — APPROVED** [review]

**Comment by sdwvit** [comment]
Thank you for contributing!

**Pull request merged**
