### PR TITLE
Fix package size

### PR DESCRIPTION
**Pull request by istarkov**
Guys we are using this package and it's huge 100+Mb unpacked in node_modules, 
It's because it contains enormous amount of garbage like examples, and even log from developer machine, unpack and see https://registry.yarnpkg.com/nylas/-/nylas-4.2.2.tgz

This PR fixes this situation making your library small and beautiful.
Please merge and publish new version, as current highly increase build times and our app size.

### CODE REVIEW

**Comment by istarkov** [comment]
PS: I haven't touched file with lint error

**Comment by khamidou** [comment]
Hi @istarkov — thanks for the pull request and apologies for this! I'm looking into this right now.

**Comment by emorikawa** [comment]
@istarkov sorry for the delay on this. Thank you so much for tracking this down.

**Comment by joanrodriguez** [comment]
Guys, 2+ months to remove garbage from npm package.... WTF
How long until it's on npm? @emorikawa @khamidou  ?

**Comment by singingwolfboy** [comment]
Version 4.2.3 has been published on NPM, which includes this change. Thanks for your patience, everyone.

**Pull request merged**
